<?php

return array(
	'label'                 => __( 'Institution', 'riffeac' ),
	'description'           => __( 'Description Institution', 'riffeac' ),
	'labels'                => array(
		'name'                  => _x( 'Institutions', 'Post Type General Name', 'riffeac' ),
		'singular_name'         => _x( 'Institutions', 'Post Type Singular Name', 'riffeac' ),
		'menu_name'             => __( 'Institutions', 'riffeac' ),
		'name_admin_bar'        => __( 'Institution', 'riffeac' ),
		'archives'              => __( 'Item Archives', 'riffeac' ),
		'attributes'            => __( 'Item Attributes', 'riffeac' ),
		'parent_item_colon'     => __( 'Parent Item:', 'riffeac' ),
		'all_items'             => __( 'Toutes les institutions', 'riffeac' ),
		'add_new_item'          => __( 'Ajouter une nouvelle institution', 'riffeac' ),
		'add_new'               => __( 'Ajouter', 'riffeac' ),
		'new_item'              => __( 'Nouvelle institution', 'riffeac' ),
		'edit_item'             => __( 'Editer une institution', 'riffeac' ),
		'update_item'           => __( 'Mettre à jour une institution', 'riffeac' ),
		'view_item'             => __( 'Voir l\'institution', 'riffeac' ),
		'view_items'            => __( 'Voir les institutions', 'riffeac' ),
		'search_items'          => __( 'Chercher une institution', 'riffeac' ),
		'not_found'             => __( 'Not found', 'riffeac' ),
		'not_found_in_trash'    => __( 'Not found in Trash', 'riffeac' ),
		'featured_image'        => __( 'Featured Image', 'riffeac' ),
		'set_featured_image'    => __( 'Set featured image', 'riffeac' ),
		'remove_featured_image' => __( 'Remove featured image', 'riffeac' ),
		'use_featured_image'    => __( 'Use as featured image', 'riffeac' ),
		'insert_into_item'      => __( 'Insert into item', 'riffeac' ),
		'uploaded_to_this_item' => __( 'Uploaded to this item', 'riffeac' ),
		'items_list'            => __( 'Items list', 'riffeac' ),
		'items_list_navigation' => __( 'Items list navigation', 'riffeac' ),
		'filter_items_list'     => __( 'Filter items list', 'riffeac' ),
	),
	'supports'              => false,
	'hierarchical'          => false,
	'public'                => true,
	'show_ui'               => true,
	'show_in_menu'          => true,
	'menu_position'         => 5,
	'menu_icon' 			=> 'dashicons-welcome-learn-more',
	'show_in_admin_bar'     => true,
	'show_in_nav_menus'     => true,
	'can_export'            => true,
	'has_archive'           => true,
	'exclude_from_search'   => false,
	'publicly_queryable'    => true,
	'capability_type'       => 'page',
);
